---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
  labels:
    app: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: gitsuren/examplenodeapp:v1.0.0
          ports:
            - containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8090
      # Port to forward to inside the pod
      targetPort: 8888
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



